import Dashboard from '@/components/Dashboard'
import MenuManagementComponent from '@/components/MenuManagementComponent'
import Sidebar from '@/components/Sidebar'
import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>Menu | Restau</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row m-2">
        <div className="flex-row w-1/4"><Sidebar /></div>
        <div className="flex-row w-3/4 "><Dashboard /></div>

      </div>
    </>
  )
}
