import Layout from '@/components/Layout'
import MenuManagementComponent from '@/components/MenuManagementComponent'
import OrdersManagement from '@/components/OrdersManagement'
import Sidebar from '@/components/Sidebar'
import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>Menu | Restau</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <MenuManagementComponent />
      </Layout>
    </>
  )
}
