import Layout from '@/components/Layout'
import MenuManagementComponent from '@/components/MenuManagementComponent'
import Head from 'next/head'
import React from 'react'

export default function menu() {
    return (
        <div>
            <Head>
                <title>Menu | Restau</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <MenuManagementComponent />
            </Layout>
        </div>
    )
}
